### ISSUE TITLE
Clarity around asset pipeline and webpacker

### ISSUE THREAD

**Issue by schpet** [TanookiLabs/tanooki-rails-template#14]
IMO all css/javascript should be loaded with webpack[er], but this template does not make that clear and it's easy to do the more conventional install-a-frontend-lib-like-bootstrap through the Gemfile and asset pipeline. possible ways we could improve the template to guide this is to turn sprockets off, or add a basic optional bootstrap setup (via yarn) or at least an example stylesheet.

**Comment by travisp** [comment]
@schpet the default in rails 6 will be for webpacker, but this will be just for javascript. Using sprockets for CSS and images seems a bit more understandable to me, at least as a long time rails user, and is probably more intuitive others used to rails (e.g. there's at least a small learning curve to switching to webpacker helpers like `image_pack_tag` and `asset_pack_path`).

What do you think the advantage would be to turn sprockets off entirely at the moment? Does it affect the use of tools like activeadmin that use sprockets?

I'm definitely open to disabling sprockets, but I'd like to hear a clear set of advantages/disadvantages, and probably would then also need help updating the template to support this.

**Comment by schpet** [comment]
hmmm yeah i don't really enjoy fighting rails defaults:
https://github.com/rails/rails/pull/33079#issuecomment-399951955

@bolandrm what's your take on this? do you think it makes sense to continue using the asset pipeline for css and images?
